# Generated by Django 3.2.3 on 2021-05-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YgUserInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userProfile.yguser')),
                ('birth_date', models.DateTimeField(null=True)),
                ('about', models.TextField(null=True)),
                ('request', models.CharField(max_length=1000, null=True)),
                ('links', models.CharField(max_length=2000, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('marital_status', models.CharField(max_length=20, null=True)),
                ('experience', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Данные пользователя',
            },
        ),
        migrations.AlterModelOptions(
            name='yguser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
