# Generated by Django 3.2.3 on 2021-05-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_auto_20210523_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='yguser',
            name='social_data_loaded',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
