# Generated by Django 3.2.3 on 2021-05-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_yguser_social_data_loaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yguserinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
