# Generated by Django 3.2.3 on 2021-05-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_rename_user_id_yguserinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yguserinfo',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
