# Generated by Django 3.2.3 on 2021-05-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_alter_yguserinfo_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yguserinfo',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
    ]
