# Generated by Django 3.2.3 on 2021-05-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_auto_20210530_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='yggender',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ygmaritalstatus',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yglocation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
