# Generated by Django 3.2.3 on 2021-05-30 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_auto_20210530_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='YgDoctrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('full_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Учение',
                'verbose_name_plural': 'Учения',
            },
        ),
        migrations.CreateModel(
            name='YgExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Опыт практики',
                'verbose_name_plural': 'Опыт практики',
            },
        ),
        migrations.CreateModel(
            name='YgInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.CreateModel(
            name='YgPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('full_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Традиция',
                'verbose_name_plural': 'Традиции',
            },
        ),
        migrations.CreateModel(
            name='YgTradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('full_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Традиция',
                'verbose_name_plural': 'Традиции',
            },
        ),
        migrations.AlterField(
            model_name='yggender',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yglocation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ygmaritalstatus',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.ygexperience'),
        ),
    ]
