# Generated by Django 3.2.3 on 2021-05-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_auto_20210530_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='yguserinfo',
            name='doctrines',
            field=models.ManyToManyField(blank=True, null=True, to='userProfile.YgDoctrine'),
        ),
    ]
