# Generated by Django 3.2.3 on 2021-05-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0013_yguserinfo_doctrines'),
    ]

    operations = [
        migrations.AddField(
            model_name='yguserinfo',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='userProfile.YgInterest'),
        ),
        migrations.AddField(
            model_name='yguserinfo',
            name='practices',
            field=models.ManyToManyField(blank=True, null=True, to='userProfile.YgPractice'),
        ),
        migrations.AddField(
            model_name='yguserinfo',
            name='traditions',
            field=models.ManyToManyField(blank=True, null=True, to='userProfile.YgTradition'),
        ),
    ]
