# Generated by Django 3.2.3 on 2021-06-07 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_auto_20210530_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ygpractice',
            options={'verbose_name': 'Практика', 'verbose_name_plural': 'Практики'},
        ),
        migrations.AddField(
            model_name='ygmaritalstatus',
            name='title_fem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Написание для женщин'),
        ),
        migrations.AlterField(
            model_name='ygdoctrine',
            name='full_info',
            field=models.TextField(blank=True, null=True, verbose_name='Полная информация'),
        ),
        migrations.AlterField(
            model_name='ygdoctrine',
            name='short_desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='ygdoctrine',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ygexperience',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='ygexperience',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='yggender',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='yggender',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='yginterest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='yglocation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ygmaritalstatus',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='ygmaritalstatus',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ygpractice',
            name='full_info',
            field=models.TextField(blank=True, null=True, verbose_name='Полная информация'),
        ),
        migrations.AlterField(
            model_name='ygpractice',
            name='short_desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='ygpractice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ygtradition',
            name='full_info',
            field=models.TextField(blank=True, null=True, verbose_name='Полная информация'),
        ),
        migrations.AlterField(
            model_name='ygtradition',
            name='short_desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='ygtradition',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='yguser',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.yggender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='yguser',
            name='is_online',
            field=models.BooleanField(default=False, null=True, verbose_name='Онлайн'),
        ),
        migrations.AlterField(
            model_name='yguser',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='yguser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile_pic', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='yguser',
            name='social_data_loaded',
            field=models.BooleanField(default=False, null=True, verbose_name='Загружены данные соцсети'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='doctrines',
            field=models.ManyToManyField(blank=True, to='userProfile.YgDoctrine', verbose_name='Учения'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.ygexperience', verbose_name='Опыт практики'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='interests',
            field=models.ManyToManyField(blank=True, to='userProfile.YgInterest', verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.yglocation', verbose_name='Место жительства'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.ygmaritalstatus', verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='practices',
            field=models.ManyToManyField(blank=True, to='userProfile.YgPractice', verbose_name='Практики'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='request',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ищу'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='traditions',
            field=models.ManyToManyField(blank=True, to='userProfile.YgTradition', verbose_name='Традиции'),
        ),
        migrations.AlterField(
            model_name='yguserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
